### ISSUE TITLE
error on seeding the database

### ISSUE THREAD

**Issue by leonzhao** [andrejewski/fakegoose#1]
```
opt/node/lib/node_modules/fakegoose/bin/fakegoose.js:43
  Model.seed(count, append, function(error) {
                    ^

ReferenceError: append is not defined
    at Object.<anonymous> (/opt/node/lib/node_modules/fakegoose/bin/fakegoose.js:43:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by andrejewski** [comment]
Let me know if there are any more problems. This package needs some love, but right now I don't have the time available.
